server:
  port: 8001
  servlet:
    application-display-name: service-edu


# 环境设置
spring:
  profiles:
    active: dev
  # Mysql数据库连接信息
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///guli?serverTimezone=GMT%2B8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

