# 服务端口号
server:
  port: 10001

  # 服务名
spring:
  application:
    name: canal-client

  # 环境设置：dev，test，prod
  profiles:
    active: dev

  # Mysql数据库连接信息
  datasource:
    username: canal
    password: canal
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///guli?serverTimezone=GMT%2B8
